import streamlit as st
from models.financial_engine import calculate_savings
from components.page_header import page_header


def reports_page():

    data = calculate_savings()

    page_header(
        "Financial Reports",
        "Download your latest financial summary.",
        back_target="🏠 Dashboard"
    )

    col1, col2 = st.columns(2)

    with col1:
        st.metric("Monthly Income", f"₹{data['income']:,.0f}")
        st.metric("Monthly Budget", f"₹{data['budget']:,.0f}")

    with col2:
        st.metric("Total Expenses", f"₹{data['expenses']:,.0f}")
        st.metric("Total Savings", f"₹{data['savings']:,.0f}")

    st.divider()

    report = f"""
=========================
      FINMATE AI REPORT
=========================

Monthly Income : ₹{data['income']:,.0f}

Monthly Budget : ₹{data['budget']:,.0f}

Total Expenses : ₹{data['expenses']:,.0f}

Total Savings  : ₹{data['savings']:,.0f}

=========================
Generated by FinMate AI
=========================
"""

    st.download_button(
        label="Download Report",
        data=report,
        file_name="FinMate_Report.txt",
        mime="text/plain",
        use_container_width=True
    )